### ISSUE TITLE
Prevent images from getting cut off

### ISSUE THREAD

**Issue by grahamd711** [choozn/react-parallax-mouse#1]
hi @choozn ! thanks for the awesome work on this project. we've just implemented this on our site 404 page and things are looking great. we did run into an issue when the image gets cut off on the left and right side. The images are plenty wide enough (4000px wide) and should keep scrolling instead of getting cut off by the container. Is there something that we can update to achieve this?

I tried adding 120% width to each of the `<MouseParallaxChild />` and also the `<MouseParallaxContainer />`

Here is a screenshot: [Image Cut Off](https://user-images.githubusercontent.com/4733796/142703081-fbe0fbec-9ac1-416a-b7f5-d7512d8c2975.png)

And also a video recording: https://drive.google.com/file/d/1QGXJ4KhK3BXutiXXsQk36zIKHOC0ObBA/view?usp=sharing

Thanks for any advice!

**Comment by choozn** [comment]
Hey, thanks for the feedback!
That 404 page is looking so cute :D 

That's definitely a CSS thing. Looks like the images are set to only fill out 100% of the parallax-container. Because of that, they are cutting off when the transition moves them to the side. I'll try to reproduce the issue tomorrow, it's most likely just a missing CSS property we'll have to find.

I would appreciate you staring the project if you found it helpful.

**Comment by grahamd711** [comment]
Ok good to know! I'll take a look into the styling of the images themselves. Awesome work on this project, just gave it a star!

**Comment by choozn** [comment]
Thank you for letting me know!
Hadn't had the time to check on safari yet. Will hopefully be fixed tomorrow.

**Comment by choozn** [comment]
The solution is providing the child elements with additional CSS. 

Set the width to something higher than 100%. I've used ``120%`` and it worked fine. 
Now it no longer cuts off on the right side.
Then you can center the child in the middle by using a negative ``margin-left``. The amount should be half of what you added to the 100%. In this case, that would be ``10%``.

Now inject that styling either using

updateStyles:
```js
{
width: "120%",
marginLeft: "-10%"
}
```

or using a class, in your case (Hero-module--background...):
```
{
width: 120%;
margin-left: -10%;
}
```

**Comment by choozn** [comment]
As I see, this worked out as expected. The 404-page looks awesome!
