### ISSUE TITLE
Bug in Safari 

### ISSUE THREAD

**Issue by grahamd711** [choozn/react-parallax-mouse#2]
hi @choozn opening up a new issue here to track an issue only present in Safari. Looks like the transform:translateX and translateY not functioning properly only in Safari. The same link works fine in Chrome.

The same issue is also present in your CodeSandbox example link in Safari: [Codesandbox Demo](https://codesandbox.io/embed/react-parallax-mouse-example-zjdsy?fontsize=14&hidenavigation=1&theme=dark&view=preview)

Here is dev link to of our 404 page: [dev link](https://mparticlecomgatsbymain2-4042.gtsb.io/404)

**Comment by choozn** [comment]
Thank you for letting me know!
Hadn't had the time to check on safari yet. Will hopefully be fixed tomorrow.

**Comment by choozn** [comment]
Hey, what exactly do you mean by "not functioning properly"?
I've done some testing using browserstack, and so far it worked fine for me. 
It would be awesome if you could provide me with some additional info, so I can get that nasty compatibility bug out of the project :D

**Comment by choozn** [comment]
Just released [Stable Version 1.3.1](https://github.com/choozn/react-parallax-mouse/releases/tag/1.3.1).
Hopefully that resolves the bug in safari.

**Comment by grahamd711** [comment]
Legend @choozn! Confirming this bug is fixed in v1.3.1. Thank you so much for the quick improvement!
