### ISSUE TITLE
Cannot work with vite

### ISSUE THREAD

**Issue by zouhangwithsweet** [choozn/react-parallax-mouse#28]
Here is mini reproduction https://stackblitz.com/edit/vitejs-vite-p9ymcn?file=src/App.tsx

**Comment by choozn** [comment]
Hey, thank you for letting me know! ``react-motion-prefixed`` is the React 17 port of ``react-motion`` without a console warning. It is supposed to be a temporary solution - as soon as I find time this package will become independent from ``react-motion``.
Sorry for any inconveniences that might cause.

**Comment by choozn** [comment]
This bug has been fixed with the release of [2.0.0](https://github.com/choozn/react-parallax-mouse/releases/tag/2.0.0).
