### ISSUE TITLE
Stop animation when mouse movement stops

### ISSUE THREAD

**Issue by grahamd711** [choozn/react-parallax-mouse#3]
Hi @choozn ! I'm trying to find a way to stop the animation (translateX, translateY) when the mouse movement stops. Currently, even when the mouse movement stops, the children still animate towards the mouse cursor. 

I've tried adjusting the springConfig but I don't think any of the React Motion helpers will fix this. Below are Gist to our 404 page component. I increased the stiffness, but this prevented the start of the motion and not the end. Ideally, I'd like to be able to control how quickly the animation stops on mouse movement stop.

Hero.js component: https://gist.github.com/grahamd711/78ac441ff2b718dc702f106e816a78a9

Hero.scss: https://gist.github.com/grahamd711/d917772b3751737f716f7e15e47615c4

Here is the preview link so you can see the motion that I'm describing: https://mparticlecomgatsbymain2-4042.gtsb.io/404

The motion would stop when mouse over ends similar to this example: https://codepen.io/envoy47/pen/OKVyer

Thanks for any advice you have!

**Comment by choozn** [comment]
Hm, that's a hard one. It's definitely a react-spring thing, as react-parallax-mouse doesn't control the form of the animation.
I might switch away from react motion in a future version, to provide better control over the animation and to shrink the bundle size, but until then you'll have to figure that out in the react-spring cosmos. Sorry.

http://chenglou.github.io/react-motion/demos/demo5-spring-parameters-chooser/ might help you.
