### ISSUE TITLE
 t.SpringValue is not a constructor

### ISSUE THREAD

**Issue by peterp96** [choozn/react-parallax-mouse#34]
Getting ` t.SpringValue is not a constructor  at ./node_modules/react-parallax-mouse/dist/index.js`.

![image](https://github.com/choozn/react-parallax-mouse/assets/68678918/0fe5b439-84fc-47a7-995b-5d0ca43b8a46)

tried with:
- react: v17.x.x, v18.x.x
- node: v14.x.x, v16.x.x, v18.x.x

still getting same error.

**Comment by choozn** [comment]
Hey @peterp96,
thanks for the bug report! Which version of react-parallax-mouse are you using?

**Comment by peterp96** [comment]
I'm using `react-parallax-mouse@2.0.1` & `react@^18.2.0`.

**Comment by choozn** [comment]
Could you please provide your package.json so we can exclude the possibility of a dependency mismatch? Thanks!

**Comment by peterp96** [comment]
Sure, here it is:

```
{
    "name": "demo-animation",
    "version": "0.1.0",
    "private": true,
    "dependencies": {
        "@testing-library/jest-dom": "^5.16.5",
        "@testing-library/react": "^13.4.0",
        "@testing-library/user-event": "^13.5.0",
        "aos": "^3.0.0-beta.6",
        "bootstrap": "^5.3.0",
        "d3-dsv": "^1.0.8",
        "d3-format": "^1.2.1",
        "d3-scale": "^1.0.7",
        "d3-time-format": "^2.1.1",
        "node-sass": "^8.0.0",
        "react": "^18.2.0",
        "react-bootstrap": "^2.7.4",
        "react-bootstrap-table-next": "^4.0.3",
        "react-bootstrap-table2-paginator": "^2.1.2",
        "react-dom": "^18.2.0",
        "react-lottie": "^1.2.3",
        "react-parallax-mouse": "^2.0.1",
        "react-router-dom": "^6.12.0",
        "react-scripts": "5.0.1",
        "react-slick": "^0.29.0",
        "react-stockcharts": "^0.7.8",
        "slick-carousel": "^1.8.1",
        "web-vitals": "^2.1.4",
        "wowjs": "^1.1.3"
    },
    "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject"
    },
    "eslintConfig": {
        "extends": [
            "react-app",
            "react-app/jest"
        ]
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    }
}
```

**Comment by choozn** [comment]
Thanks! I'll look into this issue when I'm back home.

**Comment by choozn** [comment]
Hey @peterp96!
I was not able to reproduce this error in any way yet. Did you find a workaround? Did reinstalling node-modules help?

**Comment by willsmillie** [comment]
I also started encountering this issue a couple weeks ago... I put together a sample CRA project reproducing the bug: https://github.com/willsmillie/parallax-bug-demo

Let me know if I can provide any other info!

Thanks for looking into this!

**Comment by naemtl** [comment]
Hi @willsmillie! Did you just add those entries to the bottom of your yarn.lock file or did you replace anything in the yarn.lock as well? I'm having the same issue outlined above. Thanks!

**Comment by choozn** [comment]
I will update the version of `react-spring` in the next version of `react-mouse-parallax`. This should fix the error from above.

**Comment by choozn** [comment]
Thank you @willsmillie for helping with narrowing down the source of the error!

**Comment by vishnuur** [comment]
Hi, is there any update on this issue, am also facing the same issue
