### ISSUE TITLE
Disable Parallax for Smaller Screen Sizes

### ISSUE THREAD

**Issue by vizhang** [choozn/react-parallax-mouse#6]
First off - I love your package! It's so easy to use and the documentation on existing options is great. Thanks so much for your work :)

**Is your feature request related to a problem? Please describe.**
When I implemented the parallax effect, it has slight issues when browsing on a mobile device (ie. iPhone 12 that I use):
 - when you tap the screen, the parallax jitters (I'm guessing because it registers some sort of a mouse touch event)

**Describe the solution you'd like**
- Would love for there to be a way where we could have the option of setting a min-width for the parallax affect to be disabled at
- OR ... is it possible to register parallax motion based on device rotation instead of mouse touches when that's available?

**Describe alternatives you've considered**
I'm currently monitoring the page for "isMobile" based on window width, and then setting the FactorX to 0
        <MouseParallaxChild
          factorX={isMobile ? 0 : 0.02}
          factorY={isMobile ? 0 : 0.02}
        >
**Additional context**
I'm testing here right now: https://cegaappmain.gatsbyjs.io . Uploaded a video showing the jitters: https://drive.google.com/file/d/1_nbzSOGCNJCu54Ls1t9l4i9ZRBS-dHQk/view?usp=sharing

**Comment by choozn** [comment]
Thank you for reporting this bug! I'll see what I can do about it. Also thank you for your kind words in the beginning!

**Comment by vizhang** [comment]
Amazing, many thanks!

**Comment by choozn** [comment]
Hm, that's strange. All my tests on mobile did not have any jitter (I am on android though). 
Could you publish your version without the ```isMobile``` fix, so I can check if it is really only present on IOS? 
That would be awesome.

Device rotation will also be implemented.

**Comment by choozn** [comment]
I've published v1.5.0, which introduces the ``enabled`` prop. Now you can just pass ``!isMobile`` into ``enabled`` and the library will take care of the rest. This takes a lot of load from the browser, as setting the factors to 0 still leaves the event listeners assigned, which causes unnecessary rerenders.

I'll take a look at device rotation next.

**Comment by vizhang** [comment]
Great, i'll update now and give it a shot. I uploaded the version with no "isMobile" to a public repo here: https://github.com/vizhang/cega-debug

To try it on your phone, you can run
```
npm install
npm run develop
```
and then, create a tunnel with ngrok to open on Safari
```
ngrok http 8000
```

Oddly enough I just tried right now and the jitters went away, take a look and see if you get that too!

**Comment by choozn** [comment]
No jitter for me; But I've also experienced jitter on the desktop due to ``<React.StrictMode>`` or other DevTools (e.g. CodeSandbox). 
Was your mobile test a full build of your project, or was it on the react devserver?

**Comment by vizhang** [comment]
Just looked at the original video again, looks like it was the dev build - maybe that was what did it 🥸

**Comment by choozn** [comment]
Awesome! 
Please open up a feature request for device rotation, so I can link it when I implement it later.
