### ISSUE TITLE
Warning in console

### ISSUE THREAD

**Issue by Kirill20123** [choozn/react-parallax-mouse#7]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/43911719/161569805-6f65f8e8-05b1-4f56-aaea-648f02494989.png">

    "react": "^17.0.2",

**Comment by choozn** [comment]
Hey,
this is an issue in the react-motion library by @chenglou. 
The error is not present in production builds and does not affect the performance of this library.

https://github.com/chenglou/react-motion/issues/569

I'll most likely migrate to react-spring when I find time for it. 
Until then this warning will persist in dev builds.
