### ISSUE TITLE
Janky position updates in Safari 15.4

### ISSUE THREAD

**Issue by cvalleskey** [choozn/react-parallax-mouse#8]
**Describe the bug**
Starting with Safari 15.4 when the user moves their cursor around the X/Y values are seemingly updated sporadically, causing a "jank" effect where the children quickly move back and forth between several positions with no smooth transition.

**Video of the issue**
https://user-images.githubusercontent.com/1388515/161835041-d54b9dd0-a704-4aa9-a5ad-94ef65482f0d.mov

**To Reproduce**
1. Using Safari 15.4, go to https://codesandbox.io/embed/react-parallax-mouse-example-zjdsy?fontsize=14&hidenavigation=1&theme=dark&view=preview
2. Move your mouse around to see the issue

**Expected behavior**
A smooth translation of X/Y as seen within other browser and Safari <15.

**EDIT**
This issues appears to be the result of the transition rule applied inline: `transition: transform 1e-7s linear 0s`. Overriding this to `none` makes it appear as expected.

**Comment by choozn** [comment]
Hey,
I didn't know about this problem in Safari, thank you!

For now, there is a prop to disable the transition rule called ``disableCSSTransition`` on the ``MouseParallaxContainer``.
I will look into this and probably change the default to disable this transition feature.

Thank you for reporting!

**Comment by choozn** [comment]
This should be fixed with version 1.6.0 -> https://github.com/choozn/react-parallax-mouse/releases/tag/1.6.0
